/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as TasksDateRouteImport } from './routes/tasks/$date'
import { Route as TasksDetermineIndexRouteImport } from './routes/tasks/determine/index'
import { Route as TasksCreateIndexRouteImport } from './routes/tasks/create/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksDateRoute = TasksDateRouteImport.update({
  id: '/tasks/$date',
  path: '/tasks/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksDetermineIndexRoute = TasksDetermineIndexRouteImport.update({
  id: '/tasks/determine/',
  path: '/tasks/determine/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksCreateIndexRoute = TasksCreateIndexRouteImport.update({
  id: '/tasks/create/',
  path: '/tasks/create/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tasks/$date': typeof TasksDateRoute
  '/tasks': typeof TasksIndexRoute
  '/tasks/create': typeof TasksCreateIndexRoute
  '/tasks/determine': typeof TasksDetermineIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tasks/$date': typeof TasksDateRoute
  '/tasks': typeof TasksIndexRoute
  '/tasks/create': typeof TasksCreateIndexRoute
  '/tasks/determine': typeof TasksDetermineIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tasks/$date': typeof TasksDateRoute
  '/tasks/': typeof TasksIndexRoute
  '/tasks/create/': typeof TasksCreateIndexRoute
  '/tasks/determine/': typeof TasksDetermineIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tasks/$date'
    | '/tasks'
    | '/tasks/create'
    | '/tasks/determine'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tasks/$date' | '/tasks' | '/tasks/create' | '/tasks/determine'
  id:
    | '__root__'
    | '/'
    | '/tasks/$date'
    | '/tasks/'
    | '/tasks/create/'
    | '/tasks/determine/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TasksDateRoute: typeof TasksDateRoute
  TasksIndexRoute: typeof TasksIndexRoute
  TasksCreateIndexRoute: typeof TasksCreateIndexRoute
  TasksDetermineIndexRoute: typeof TasksDetermineIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$date': {
      id: '/tasks/$date'
      path: '/tasks/$date'
      fullPath: '/tasks/$date'
      preLoaderRoute: typeof TasksDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/determine/': {
      id: '/tasks/determine/'
      path: '/tasks/determine'
      fullPath: '/tasks/determine'
      preLoaderRoute: typeof TasksDetermineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/create/': {
      id: '/tasks/create/'
      path: '/tasks/create'
      fullPath: '/tasks/create'
      preLoaderRoute: typeof TasksCreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TasksDateRoute: TasksDateRoute,
  TasksIndexRoute: TasksIndexRoute,
  TasksCreateIndexRoute: TasksCreateIndexRoute,
  TasksDetermineIndexRoute: TasksDetermineIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
